import jsPDF from "jspdf";

const line = (doc, y) => {
  doc.setDrawColor(200);
  doc.line(14, y, 196, y);
};

export const downloadInvoicePdf = ({ doc: record, company, partyName, productName, godownName }) => {
  const pdf = new jsPDF();
  const isSale = record.doc_type !== "purchase";
  const title = isSale ? "TAX INVOICE" : "PURCHASE VOUCHER";

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(16);
  pdf.text(company?.name || "Potato ERP", 14, 20);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(company?.address || "", 14, 26);
  pdf.text(`Phone: ${company?.phone || "-"}   GSTIN: ${company?.gstin || "-"}`, 14, 31);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(13);
  pdf.text(title, 196, 20, { align: "right" });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(`No: ${record.invoice_no || "-"}`, 196, 26, { align: "right" });
  pdf.text(`Date: ${record.date || "-"}`, 196, 31, { align: "right" });

  line(pdf, 36);

  pdf.setFont("helvetica", "bold");
  pdf.text(isSale ? "Billed To" : "Received From", 14, 44);
  pdf.setFont("helvetica", "normal");
  pdf.text(partyName || "-", 14, 50);
  pdf.text(`Category: ${record.category || "-"}`, 14, 56);
  pdf.text(`Godown: ${godownName || "-"}`, 120, 50);
  pdf.text(`Lot No: ${record.lot_no || "-"}   Vehicle: ${record.vehicle_no || "-"}`, 120, 56);

  line(pdf, 62);

  const headers = ["Product", "Bags/Katta", "Weight (kg)", "Rate", "Amount"];
  const cols = [16, 70, 105, 140, 196];
  pdf.setFont("helvetica", "bold");
  headers.forEach((h, i) => pdf.text(h, cols[i], 70, { align: i === 4 ? "right" : "left" }));
  pdf.setFont("helvetica", "normal");
  const values = [
    productName || "-",
    String(record.bags ?? 0),
    String(record.weight ?? 0),
    `${record.rate ?? 0} / ${record.rate_basis === "weight" ? "kg" : "bag"}`,
    Number(record.amount || 0).toFixed(2),
  ];
  values.forEach((v, i) => pdf.text(v, cols[i], 78, { align: i === 4 ? "right" : "left" }));

  line(pdf, 84);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(11);
  pdf.text(`Total: INR ${Number(record.amount || 0).toFixed(2)}`, 196, 93, { align: "right" });

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text(`Payment Type: ${record.payment_type || "-"}`, 14, 93);
  pdf.text(`Payment Mode: ${record.payment_mode || "-"}`, 14, 99);
  if (record.cheque_no) pdf.text(`Cheque No: ${record.cheque_no}`, 14, 105);
  if (record.notes) pdf.text(`Notes: ${record.notes}`, 14, 111);

  pdf.text("Authorised Signatory", 196, 135, { align: "right" });
  pdf.setFontSize(8);
  pdf.setTextColor(130);
  pdf.text("Generated by Potato Management Software", 14, 285);

  pdf.save(`${record.invoice_no || "document"}.pdf`);
};

export const downloadLedgerPdf = ({ farmerName, entries, totals, company }) => {
  const pdf = new jsPDF();
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(15);
  pdf.text(company?.name || "Potato ERP", 14, 20);
  pdf.setFontSize(11);
  pdf.text(`Farmer Ledger - ${farmerName}`, 14, 28);
  line(pdf, 32);

  const cols = [14, 50, 120, 150, 196];
  pdf.setFontSize(9);
  ["Date", "Particulars", "Debit", "Credit", "Balance"].forEach((h, i) =>
    pdf.text(h, cols[i], 40, { align: i === 4 ? "right" : "left" })
  );
  pdf.setFont("helvetica", "normal");
  let y = 48;
  entries.forEach((e) => {
    if (y > 275) {
      pdf.addPage();
      y = 20;
    }
    pdf.text(String(e.date || "-"), cols[0], y);
    pdf.text(String(e.particulars || "-").slice(0, 40), cols[1], y);
    pdf.text(Number(e.debit || 0).toFixed(2), cols[2], y);
    pdf.text(Number(e.credit || 0).toFixed(2), cols[3], y);
    pdf.text(Number(e.balance || 0).toFixed(2), cols[4], y, { align: "right" });
    y += 7;
  });
  line(pdf, y);
  pdf.setFont("helvetica", "bold");
  pdf.text(
    `Debit: ${Number(totals.debit).toFixed(2)}   Credit: ${Number(totals.credit).toFixed(
      2
    )}   Balance: ${Number(totals.balance).toFixed(2)}`,
    196,
    y + 8,
    { align: "right" }
  );
  pdf.save(`ledger-${farmerName}.pdf`);
};

export const downloadReportPdf = ({ title, rows, totals, columns }) => {
  const pdf = new jsPDF({ orientation: "landscape" });
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.text(title, 14, 18);
  pdf.setFontSize(9);
  let x = 14;
  const widths = columns.map(() => 260 / columns.length);
  columns.forEach((c, i) => {
    pdf.text(c.label, x, 28);
    x += widths[i];
  });
  pdf.setFont("helvetica", "normal");
  let y = 35;
  rows.forEach((r) => {
    if (y > 195) {
      pdf.addPage();
      y = 20;
    }
    let cx = 14;
    columns.forEach((c, i) => {
      pdf.text(String(c.value(r) ?? "-").slice(0, 24), cx, y);
      cx += widths[i];
    });
    y += 6;
  });
  pdf.setFont("helvetica", "bold");
  pdf.text(
    `Records: ${totals.count}   Bags: ${totals.bags}   Weight: ${totals.weight}   Amount: ${Number(
      totals.amount
    ).toFixed(2)}`,
    14,
    y + 8
  );
  pdf.save(`${title.replace(/\s+/g, "-").toLowerCase()}.pdf`);
};
